

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AramarkPizzaApp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Pizza_ordersEntities : DbContext
{
    public Pizza_ordersEntities()
        : base("name=Pizza_ordersEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<customer> customers { get; set; }

    public virtual DbSet<Login> Logins { get; set; }

}

}

