
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AramarkPizzaApp
{

using System;
    using System.Collections.Generic;
    
public partial class customer
{

    public int CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerS0 { get; set; }

    public string Order { get; set; }

    public decimal Cost { get; set; }

}

}
